Disable Ubuntu and Mac OS build jobs in workflow
Comment out the build steps related to ubuntu and macOS in the workflow to focus on Windows builds only.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,97 +21,97 @@ env:
   CONAN_VERSION: 2.11.0
 
 jobs:
-  build-ubuntu-docker:
-    # Our Ubuntu builds are built using Docker images that have been pre-published.
-    # This speeds up builds for us since we do some pre-building of packages that takes a long time
-    # However, this means if you need to add a dependency to the build, you'll need to do that
-    # in the https://github.com/Chatterino/docker repository first.
-    name: "Build Ubuntu in Docker"
-    runs-on: ubuntu-latest
-    container: ${{ matrix.container }}
-    strategy:
-      matrix:
-        include:
-          - os: ubuntu-20.04
-            container: ghcr.io/chatterino/chatterino2-build-ubuntu-20.04:latest
-            qt-version: 6.7.2
-            force-lto: false
-            skip-artifact: false
-            skip-crashpad: false
-            build-deb: true
-          - os: ubuntu-22.04
-            container: ghcr.io/chatterino/chatterino2-build-ubuntu-22.04:latest
-            qt-version: 6.7.2
-            force-lto: false
-            skip-artifact: false
-            skip-crashpad: false
-            build-deb: true
-          - os: ubuntu-24.04
-            container: ghcr.io/chatterino/chatterino2-build-ubuntu-24.04:latest
-            qt-version: 6.7.2
-            force-lto: false
-            skip-artifact: false
-            skip-crashpad: false
-            build-deb: true
-    env:
-      C2_ENABLE_LTO: ${{ matrix.force-lto }}
-      C2_ENABLE_CRASHPAD: ${{ matrix.skip-crashpad == false }}
+  # build-ubuntu-docker:
+  #   # Our Ubuntu builds are built using Docker images that have been pre-published.
+  #   # This speeds up builds for us since we do some pre-building of packages that takes a long time
+  #   # However, this means if you need to add a dependency to the build, you'll need to do that
+  #   # in the https://github.com/Chatterino/docker repository first.
+  #   name: "Build Ubuntu in Docker"
+  #   runs-on: ubuntu-latest
+  #   container: ${{ matrix.container }}
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - os: ubuntu-20.04
+  #           container: ghcr.io/chatterino/chatterino2-build-ubuntu-20.04:latest
+  #           qt-version: 6.7.2
+  #           force-lto: false
+  #           skip-artifact: false
+  #           skip-crashpad: false
+  #           build-deb: true
+  #         - os: ubuntu-22.04
+  #           container: ghcr.io/chatterino/chatterino2-build-ubuntu-22.04:latest
+  #           qt-version: 6.7.2
+  #           force-lto: false
+  #           skip-artifact: false
+  #           skip-crashpad: false
+  #           build-deb: true
+  #         - os: ubuntu-24.04
+  #           container: ghcr.io/chatterino/chatterino2-build-ubuntu-24.04:latest
+  #           qt-version: 6.7.2
+  #           force-lto: false
+  #           skip-artifact: false
+  #           skip-crashpad: false
+  #           build-deb: true
+  #   env:
+  #     C2_ENABLE_LTO: ${{ matrix.force-lto }}
+  #     C2_ENABLE_CRASHPAD: ${{ matrix.skip-crashpad == false }}
 
-    steps:
-      - uses: actions/checkout@v5
-        with:
-          submodules: recursive
-          fetch-depth: 0 # allows for tags access
+  #   steps:
+  #     - uses: actions/checkout@v5
+  #       with:
+  #         submodules: recursive
+  #         fetch-depth: 0 # allows for tags access
 
-      - name: Fix git permission error
-        run: |
-          git config --global --add safe.directory '*'
+  #     - name: Fix git permission error
+  #       run: |
+  #         git config --global --add safe.directory '*'
 
-      - name: Install Python and libclang (24.04)
-        if: matrix.os == 'ubuntu-24.04'
-        run: |
-          sudo apt update
-          sudo DEBIAN_FRONTEND=noninteractive apt -y --no-install-recommends install \
-            python3 python3-venv clang-18 clang-format-18 libclang-18-dev
-          echo "LIBCLANG_LIBRARY_FILE=/usr/lib/x86_64-linux-gnu/libclang-18.so" >> "$GITHUB_ENV"
-          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 42
-          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 42
+  #     - name: Install Python and libclang (24.04)
+  #       if: matrix.os == 'ubuntu-24.04'
+  #       run: |
+  #         sudo apt update
+  #         sudo DEBIAN_FRONTEND=noninteractive apt -y --no-install-recommends install \
+  #           python3 python3-venv clang-18 clang-format-18 libclang-18-dev
+  #         echo "LIBCLANG_LIBRARY_FILE=/usr/lib/x86_64-linux-gnu/libclang-18.so" >> "$GITHUB_ENV"
+  #         sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 42
+  #         sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 42
 
-      - name: Build
-        run: |
-          mkdir build
-          cd build
-          CXXFLAGS=-fno-sized-deallocation cmake \
-            -DCMAKE_INSTALL_PREFIX=appdir/usr/ \
-            -DCMAKE_BUILD_TYPE=Release \
-            -DPAJLADA_SETTINGS_USE_BOOST_FILESYSTEM=On \
-            -DUSE_PRECOMPILED_HEADERS=OFF \
-            -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
-            -DCHATTERINO_LTO="$C2_ENABLE_LTO" \
-            -DCMAKE_PREFIX_PATH="$Qt6_DIR/lib/cmake" \
-            -DCHATTERINO_STATIC_QT_BUILD=On \
-            -DFORCE_JSON_GENERATION=${{matrix.os == 'ubuntu-24.04' && 'On' || 'Off'}} \
-            ..
-          make -j"$(nproc)"
+  #     - name: Build
+  #       run: |
+  #         mkdir build
+  #         cd build
+  #         CXXFLAGS=-fno-sized-deallocation cmake \
+  #           -DCMAKE_INSTALL_PREFIX=appdir/usr/ \
+  #           -DCMAKE_BUILD_TYPE=Release \
+  #           -DPAJLADA_SETTINGS_USE_BOOST_FILESYSTEM=On \
+  #           -DUSE_PRECOMPILED_HEADERS=OFF \
+  #           -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
+  #           -DCHATTERINO_LTO="$C2_ENABLE_LTO" \
+  #           -DCMAKE_PREFIX_PATH="$Qt6_DIR/lib/cmake" \
+  #           -DCHATTERINO_STATIC_QT_BUILD=On \
+  #           -DFORCE_JSON_GENERATION=${{matrix.os == 'ubuntu-24.04' && 'On' || 'Off'}} \
+  #           ..
+  #         make -j"$(nproc)"
 
-      - name: Check generated sources
-        if: matrix.os == 'ubuntu-24.04'
-        run: |
-          git add -N lib/twitch-eventsub-ws/include lib/twitch-eventsub-ws/src
-          git --no-pager diff --exit-code lib/twitch-eventsub-ws/include lib/twitch-eventsub-ws/src
+  #     - name: Check generated sources
+  #       if: matrix.os == 'ubuntu-24.04'
+  #       run: |
+  #         git add -N lib/twitch-eventsub-ws/include lib/twitch-eventsub-ws/src
+  #         git --no-pager diff --exit-code lib/twitch-eventsub-ws/include lib/twitch-eventsub-ws/src
 
-      - name: Package - .deb (Ubuntu)
-        if: matrix.build-deb
-        run: |
-          cd build
-          sh ./../.CI/CreateUbuntuDeb.sh
+  #     - name: Package - .deb (Ubuntu)
+  #       if: matrix.build-deb
+  #       run: |
+  #         cd build
+  #         sh ./../.CI/CreateUbuntuDeb.sh
 
-      - name: Upload artifact - .deb (Ubuntu)
-        if: matrix.build-deb
-        uses: actions/upload-artifact@v4
-        with:
-          name: Chatterino-${{ matrix.os }}-Qt-${{ matrix.qt-version }}.deb
-          path: build/Chatterino-${{ matrix.os }}-x86_64.deb
+  #     - name: Upload artifact - .deb (Ubuntu)
+  #       if: matrix.build-deb
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: Chatterino-${{ matrix.os }}-Qt-${{ matrix.qt-version }}.deb
+  #         path: build/Chatterino-${{ matrix.os }}-x86_64.deb
 
   build:
     name: "Build ${{ matrix.os }}, Qt ${{ matrix.qt-version }} (LTO:${{ matrix.force-lto }}, crashpad:${{ matrix.skip-crashpad && 'off' || 'on' }})"
@@ -259,52 +259,53 @@ jobs:
         run: conan cache clean --source --build --download "*"
         shell: bash
 
-      # MACOS
-      - name: Install dependencies (MacOS)
-        if: startsWith(matrix.os, 'macos')
-        run: |
-          # brew install openssl rapidjson p7zip create-dmg cmake tree boost
-          brew install openssl rapidjson p7zip create-dmg tree boost
-        shell: bash
+      # # MACOS
+      # - name: Install dependencies (MacOS)
+      #   if: startsWith(matrix.os, 'macos')
+      #   run: |
+      #     # brew install openssl rapidjson p7zip create-dmg cmake tree boost
+      #     brew install openssl rapidjson p7zip create-dmg tree boost
+      #   shell: bash
 
-      - name: Build (MacOS)
-        if: startsWith(matrix.os, 'macos')
-        run: |
-          mkdir build
-          cd build
-          cmake \
-              -DCMAKE_BUILD_TYPE=Release \
-              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
-              -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl \
-              -DUSE_PRECOMPILED_HEADERS=OFF \
-              -DCHATTERINO_LTO="$C2_ENABLE_LTO" \
-              -DFORCE_JSON_GENERATION=Off \
-              ..
-          make -j"$(sysctl -n hw.logicalcpu)"
-        shell: bash
+      # - name: Build (MacOS)
+      #   if: startsWith(matrix.os, 'macos')
+      #   run: |
+      #     mkdir build
+      #     cd build
+      #     cmake \
+      #         -DCMAKE_BUILD_TYPE=Release \
+      #         -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
+      #         -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl \
+      #         -DUSE_PRECOMPILED_HEADERS=OFF \
+      #         -DCHATTERINO_LTO="$C2_ENABLE_LTO" \
+      #         -DFORCE_JSON_GENERATION=Off \
+      #         ..
+      #     make -j"$(sysctl -n hw.logicalcpu)"
+      #   shell: bash
 
-      - name: Package (MacOS)
-        if: startsWith(matrix.os, 'macos')
-        env:
-          OUTPUT_DMG_PATH: chatterino-macos-Qt-${{ matrix.qt-version}}.dmg
-        run: |
-          ls -la
-          pwd
-          ls -la build || true
-          cd build
-          ./../.CI/MacDeploy.sh
-          ./../.CI/CreateDMG.sh
-        shell: bash
+      # - name: Package (MacOS)
+      #   if: startsWith(matrix.os, 'macos')
+      #   env:
+      #     OUTPUT_DMG_PATH: chatterino-macos-Qt-${{ matrix.qt-version}}.dmg
+      #   run: |
+      #     ls -la
+      #     pwd
+      #     ls -la build || true
+      #     cd build
+      #     ./../.CI/MacDeploy.sh
+      #     ./../.CI/CreateDMG.sh
+      #   shell: bash
 
-      - name: Upload artifact (MacOS)
-        if: startsWith(matrix.os, 'macos')
-        uses: actions/upload-artifact@v4
-        with:
-          name: chatterino-macos-Qt-${{ matrix.qt-version }}.dmg
-          path: build/chatterino-macos-Qt-${{ matrix.qt-version }}.dmg
+      # - name: Upload artifact (MacOS)
+      #   if: startsWith(matrix.os, 'macos')
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: chatterino-macos-Qt-${{ matrix.qt-version }}.dmg
+      #     path: build/chatterino-macos-Qt-${{ matrix.qt-version }}.dmg
 
+# Remome 'build-ubuntu-docker' from the 'needs' list, only build Windows Versions
   create-release:
-    needs: [build-ubuntu-docker, build]
+    needs: [build]
     runs-on: ubuntu-latest
     if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
 
@@ -326,29 +327,29 @@ jobs:
           name: chatterino-windows-old-x86-64-Qt-6.7.3-symbols.pdb.7z
           path: release-artifacts/
 
-      # Linux
-      - uses: actions/download-artifact@v5
-        name: Ubuntu 20.04 deb
-        with:
-          name: Chatterino-ubuntu-20.04-Qt-6.7.2.deb
-          path: release-artifacts/
+      # # Linux
+      # - uses: actions/download-artifact@v5
+      #   name: Ubuntu 20.04 deb
+      #   with:
+      #     name: Chatterino-ubuntu-20.04-Qt-6.7.2.deb
+      #     path: release-artifacts/
 
-      - uses: actions/download-artifact@v5
-        name: Ubuntu 22.04 deb
-        with:
-          name: Chatterino-ubuntu-22.04-Qt-6.7.2.deb
-          path: release-artifacts/
+      # - uses: actions/download-artifact@v5
+      #   name: Ubuntu 22.04 deb
+      #   with:
+      #     name: Chatterino-ubuntu-22.04-Qt-6.7.2.deb
+      #     path: release-artifacts/
 
-      - uses: actions/download-artifact@v5
-        name: Ubuntu 24.04 deb
-        with:
-          name: Chatterino-ubuntu-24.04-Qt-6.7.2.deb
-          path: release-artifacts/
+      # - uses: actions/download-artifact@v5
+      #   name: Ubuntu 24.04 deb
+      #   with:
+      #     name: Chatterino-ubuntu-24.04-Qt-6.7.2.deb
+      #     path: release-artifacts/
 
-      - name: Copy flatpakref
-        run: |
-          cp .CI/chatterino-nightly.flatpakref release-artifacts/
-        shell: bash
+      # - name: Copy flatpakref
+      #   run: |
+      #     cp .CI/chatterino-nightly.flatpakref release-artifacts/
+      #   shell: bash
 
       - name: Setup Python
         uses: actions/setup-python@v6
